In [2]:
#Importing libraries
import streamlit as st 
import pandas as pd
import numpy as np
import seaborn as sns
import altair as alt
import matplotlib.pyplot as plt

In [3]:
# Cache 
@st.cache_data
def load_data(csv):
    df = pd.read_csv(csv) 
    return df

2024-05-06 14:43:16.941 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [31]:
#Reading in the data 
provisional_death=pd.read_csv('provisional_death.csv')
#removing commas FOR DATA VALUE AND PREDICTED 
provisional_death[['Data Value', 'Predicted Value']].replace(',', '', regex=True, inplace=True)


#describing data 
provisional_death.head()

C:\Users\Lizet\AppData\Local\Temp\ipykernel_18984\1481573822.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provisional_death[['Data Value', 'Predicted Value']].replace(',', '', regex=True, inplace=True)

,State,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State Name,Predicted Value
0,AK,2015,April,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",0,100,0.0,Alaska,0
1,AK,2015,April,12 month-ending,Heroin (T40.1),0,100,0.0,Alaska,0
2,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),0,100,0.0,Alaska,0
3,AK,2015,April,12 month-ending,Number of Drug Overdose Deaths,126,100,0.0,Alaska,126
4,AK,2015,April,12 month-ending,Cocaine (T40.5),0,100,0.0,Alaska,0

In [32]:
#Checking for null values & columns 
provisional_death.isnull()
provisional_death.isna().sum()

State                            0
Year                             0
Month                            0
Period                           0
Indicator                        0
Data Value                       0
Percent Complete                 0
Percent Pending Investigation    0
State Name                       0
Predicted Value                  0
dtype: int64

In [33]:
#Checking data types 
print(provisional_death.dtypes)
provisional_death.shape

State                             object
Year                               int64
Month                             object
Period                            object
Indicator                         object
Data Value                         int64
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                    int64
dtype: object

(65163, 10)

In [35]:
# #Need to run it only once - Dropping footnote & symbol
# provisional_death=provisional_death.drop(['Footnote','Footnote Symbol'],axis=1)

In [36]:
#Checking data types 
print(provisional_death.dtypes)
provisional_death.shape

State                             object
Year                               int64
Month                             object
Period                            object
Indicator                         object
Data Value                         int64
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                    int64
dtype: object

(65163, 10)

In [37]:
# Fill 0 for missing values 
provisional_death=provisional_death.fillna(0)

In [38]:
#No missing values 
provisional_death.isna().sum()

State                            0
Year                             0
Month                            0
Period                           0
Indicator                        0
Data Value                       0
Percent Complete                 0
Percent Pending Investigation    0
State Name                       0
Predicted Value                  0
dtype: int64

In [11]:
# Can delete later - out of order 
#provisional_death['Date'] = provisional_death['Date'].astype('int64').astype('int32')

#provisional_death['Date'] = pd.to_datetime(provisional_death['Date']).astype(int.64)

In [12]:
# #No need for date column
# # Converting Year & Month to string and creating a column called Date
# provisional_death['Year'] = provisional_death['Year'].astype(str)
# provisional_death["Month"]= provisional_death['Month'].astype(str)

# # Creating date column 
# provisional_death["Date"] = provisional_death["Month"] + " " + provisional_death["Year"]
# # Taking a look at the new dataframe
# provisional_death.head()

In [39]:
# Converting Year & Month to Integers & Strings 
provisional_death['Year'] = provisional_death['Year'].astype(str).str.replace(',', '').astype(int)
provisional_death["Month"]= provisional_death['Month'].astype(str)

In [40]:
#Checking to see if conversion is successful 
provisional_death.dtypes

State                             object
Year                               int32
Month                             object
Period                            object
Indicator                         object
Data Value                         int64
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                    int64
dtype: object

In [41]:
# Converting 'Data Value' and 'Predicted Value' to string
provisional_death['Data Value'] = provisional_death['Data Value'].astype(str)
provisional_death['Predicted Value'] = provisional_death['Predicted Value'].astype(str)


#REMOVING COMMAS AND CONVERT TO FLOATS
provisional_death['Data Value'] = provisional_death['Data Value'].str.replace(',', '').astype(float)
provisional_death['Predicted Value'] = provisional_death['Predicted Value'].str.replace(',', '').astype(float)

# Convert float values to integers
provisional_death['Data Value'] = provisional_death['Data Value'].astype(int)
provisional_death['Predicted Value'] = provisional_death['Predicted Value'].astype(int)

In [42]:
print(provisional_death.dtypes)
print(provisional_death.isna().sum())
print(provisional_death)

State                             object
Year                               int32
Month                             object
Period                            object
Indicator                         object
Data Value                         int32
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                    int32
dtype: object
State                            0
Year                             0
Month                            0
Period                           0
Indicator                        0
Data Value                       0
Percent Complete                 0
Percent Pending Investigation    0
State Name                       0
Predicted Value                  0
dtype: int64
      State  Year      Month           Period  \
0        AK  2015      April  12 month-ending
1        AK  2015      April  12 month-ending
2        AK  2015      April  12 month-ending
3        AK  2015      April  12 month-ending
4        AK  2015      April  12 month-ending
...     ...   ...        ...              ...
65158    YC  2023  September  12 month-ending
65159    YC  2023  September  12 month-ending
65160    YC  2023  September  12 month-ending
65161    YC  2023  September  12 month-ending
65162    YC  2023  September  12 month-ending

                                           Indicator  Data Value  \
0         Synthetic opioids, excl. methadone (T40.4)           0
1                                     Heroin (T40.1)           0
2           Natural & semi-synthetic opioids (T40.2)           0
3                     Number of Drug Overdose Deaths         126
4                                    Cocaine (T40.5)           0
...                                              ...         ...
65158                   Percent with drugs specified          99
65159     Synthetic opioids, excl. methadone (T40.4)        2584
65160                                Cocaine (T40.5)        1670
65161                               Number of Deaths       56377
65162  Psychostimulants with abuse potential (T43.6)         252

      Percent Complete  Percent Pending Investigation     State Name  \
0                  100                       0.000000         Alaska
1                  100                       0.000000         Alaska
2                  100                       0.000000         Alaska
3                  100                       0.000000         Alaska
4                  100                       0.000000         Alaska
...                ...                            ...            ...
65158              100                       0.297994  New York City
65159              100                       0.297994  New York City
65160              100                       0.297994  New York City
65161              100                       0.297994  New York City
65162              100                       0.297994  New York City

       Predicted Value
0                    0
1                    0
2                    0
3                  126
4                    0
...                ...
65158                0
65159             2678
65160             1728
65161                0
65162              262

[65163 rows x 10 columns]

In [17]:
####################      TAKE 1 #########################
# # Define a dictionary mapping month names to their corresponding numerical representation
# month_dict = {'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
#               'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12}

# # Map month names to numerical values
# provisional_death['Month'] = provisional_death['Month'].map(month_dict)

# # Convert month names to date format
# provisional_death['Month'] = pd.to_datetime(provisional_death['Month'], format='%m').dt.strftime('%B')

# # Display the DataFrame
# print(provisional_death)


#############     TAKE 2 ##################
# Define a dictionary mapping month names to their corresponding numerical representation
# month_dict = {'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
#               'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12}

# # Map month names to numerical values
# provisional_death['Month'] = provisional_death['Month'].map(month_dict)

# # Convert numerical month representation to datetime object
# provisional_death['Month'] = pd.to_datetime(provisional_death['Month'], format='%m')

# # Display the DataFrame
# print(provisional_death)

###############   TAKE 3 ######################
# Convert month names to date format
#provisional_death['Month'] = pd.to_datetime(provisional_death['Month'], format='%B')

# Display the DataFrame
#print(provisional_death)

In [43]:
provisional_death.dtypes

State                             object
Year                               int32
Month                             object
Period                            object
Indicator                         object
Data Value                         int32
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                    int32
dtype: object

In [44]:
# Creating  a new csv file - cleaned 
#Assuming your DataFrame is named 'provisional_death'
# Replace 'provisional_death.csv' with the desired filename for your CSV file

provisional_death.to_csv('provisional_death.csv', index=False)

In [45]:
# Converting 'Data Value' and 'Predicted Value' to string
provisional_death['Data Value'] = provisional_death['Data Value'].astype(str)
provisional_death['Predicted Value'] = provisional_death['Predicted Value'].astype(str)

In [46]:

# Data value and Predicted value to integers 
provisional_death['Data Value'].fillna(0, inplace=True)
provisional_death['Predicted Value'].fillna(0, inplace=True)

# Remove commas and convert to float
provisional_death['Data Value'] = provisional_death['Data Value'].str.replace(',', '').astype(float)
provisional_death['Predicted Value'] = provisional_death['Predicted Value'].str.replace(',', '').astype(float)

# Checking if the conversion is successful
print(provisional_death)

      State  Year      Month           Period  \
0        AK  2015      April  12 month-ending
1        AK  2015      April  12 month-ending
2        AK  2015      April  12 month-ending
3        AK  2015      April  12 month-ending
4        AK  2015      April  12 month-ending
...     ...   ...        ...              ...
65158    YC  2023  September  12 month-ending
65159    YC  2023  September  12 month-ending
65160    YC  2023  September  12 month-ending
65161    YC  2023  September  12 month-ending
65162    YC  2023  September  12 month-ending

                                           Indicator  Data Value  \
0         Synthetic opioids, excl. methadone (T40.4)         0.0
1                                     Heroin (T40.1)         0.0
2           Natural & semi-synthetic opioids (T40.2)         0.0
3                     Number of Drug Overdose Deaths       126.0
4                                    Cocaine (T40.5)         0.0
...                                              ...         ...
65158                   Percent with drugs specified        99.0
65159     Synthetic opioids, excl. methadone (T40.4)      2584.0
65160                                Cocaine (T40.5)      1670.0
65161                               Number of Deaths     56377.0
65162  Psychostimulants with abuse potential (T43.6)       252.0

      Percent Complete  Percent Pending Investigation     State Name  \
0                  100                       0.000000         Alaska
1                  100                       0.000000         Alaska
2                  100                       0.000000         Alaska
3                  100                       0.000000         Alaska
4                  100                       0.000000         Alaska
...                ...                            ...            ...
65158              100                       0.297994  New York City
65159              100                       0.297994  New York City
65160              100                       0.297994  New York City
65161              100                       0.297994  New York City
65162              100                       0.297994  New York City

       Predicted Value
0                  0.0
1                  0.0
2                  0.0
3                126.0
4                  0.0
...                ...
65158              0.0
65159           2678.0
65160           1728.0
65161              0.0
65162            262.0

[65163 rows x 10 columns]

C:\Users\Lizet\AppData\Local\Temp\ipykernel_18984\751261102.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  provisional_death['Data Value'].fillna(0, inplace=True)
C:\Users\Lizet\AppData\Local\Temp\ipykernel_18984\751261102.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  provisional_death['Predicted Value'].fillna(0, inplace=True)

In [47]:
# Code from internet summary statistics 
summary_stats=provisional_death.describe() 
print(summary_stats)


#sns.scatterplot(x='Data_Value', y='Predicted_Value')
#plt.title('Scatter Plot: Data Value vs Predicted Value')
#plt.xlabel('Data_Value')
#plt.ylabel('Predicted_Value')
#plt.show()

# Trying to plot a scatter plot 
def scatter_plot(file,x,y,title):
     return alt.Chart(file,title=title).mark_circle().encode(
        x=x,
        y=y,
        tooltip=[x,y,'Data_value']
    ).interactive()

               Year    Data Value  Percent Pending Investigation  \
count  65163.000000  6.516300e+04                   65163.000000
mean    2018.962617  1.080318e+04                       0.117019
std        2.564789  1.241956e+05                       0.159956
min     2015.000000  0.000000e+00                       0.000000
25%     2017.000000  3.900000e+01                       0.017082
50%     2019.000000  1.730000e+02                       0.054563
75%     2021.000000  8.560000e+02                       0.158812
max     2023.000000  3.538076e+06                       2.178273

       Predicted Value
count     65163.000000
mean        952.025290
std        5376.594875
min           0.000000
25%           0.000000
50%          86.000000
75%         462.000000
max      113127.000000

In [23]:
# # code from internet outliers (NOT WORKING)
# def detect_outliers_iqr(provisional_death):
#     # Convert data to numeric type (assuming it's convertible)
#     try:
#         provisional_death = np.array(provisional_death, dtype=float)
#     except ValueError:
#         print("Error: Unable to convert data to numeric type")
#         return None

#     # Calculate q1 & q3 
#     q1 = np.percentile(provisional_death, 25)
#     q3 = np.percentile(provisional_death, 75)

#     # Calculate IQR
#     IQR = q3 - q1

#     # Calculate lower & upper bounds
#     lower_bound = q1 - 1.5 * IQR
#     upper_bound = q3 + 1.5 * IQR

#     # Identify outliers
#     outliers = (provisional_death < lower_bound) | (provisional_death > upper_bound)
    
#     return outliers
# outlier_values = detect_outliers_iqr(provisional_death)
# print("Outlier values:", outlier_values)

In [24]:
# # Interquartile Range (IQR) Method
# Q1 = provisional_death['Data Value'].quantile(0.25)
# Q3 = provisional_death['Data Value'].quantile(0.75)
# IQR = Q3 - Q1
# lower_bound = Q1 - 1.5 * IQR
# upper_bound = Q3 + 1.5 * IQR

# outliers_IQR = provisional_death[(provisional_death['Data Value'] < lower_bound) | (provisional_death['Data Value'] > upper_bound)]

# # Z-score Method
# from scipy import stats

# z_scores = stats.zscore(provisional_death['Data Value'])
# threshold = 3
# outliers_Z = provisional_death[abs(z_scores) > threshold]

# print("Outliers using IQR Method:")
# print(outliers_IQR)
# print("\nOutliers using Z-score Method:")
# print(outliers_Z)

In [48]:
provisional_death['Date'] = pd.to_datetime(provisional_death['Date'])

KeyError: 'Date'

In [49]:
provisional_death.dtypes

State                             object
Year                               int32
Month                             object
Period                            object
Indicator                         object
Data Value                       float64
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                  float64
dtype: object

In [50]:
print(provisional_death['Month'].unique())

['April' 'August' 'December' 'February' 'January' 'July' 'June' 'March'
 'May' 'November' 'October' 'September']

In [51]:
# Find rows causing parsing errors
error_rows = provisional_death[pd.to_datetime(provisional_death["Date"], errors='coerce').isnull()]

# Print the rows causing parsing errors
print(error_rows)

KeyError: 'Date'

In [52]:
provisional_death.dtypes

State                             object
Year                               int32
Month                             object
Period                            object
Indicator                         object
Data Value                       float64
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                  float64
dtype: object

In [64]:
provisional_death['Year'] = provisional_death['Year'].astype(str)
provisional_death["Month"]= provisional_death['Month'].astype(str)



def parse_date(date_string):
    try:
        # Try parsing with format='%Y-%b' for year-month abbreviation (e.g., 2015-Apr)
        return pd.to_datetime(date_string, format='%Y-%b')
    except ValueError:
        try:
            # If the first attempt fails, try parsing with format='%Y-%B' for full month name (e.g., 2015-April)
            return pd.to_datetime(date_string, format='%Y-%B')
        except ValueError:
            # If both attempts fail, return NaT (Not a Time)
            return pd.NaT

provisional_death["Date"] = provisional_death["Year"] + "-" + provisional_death["Month"]

# Apply the custom parsing function to each element in the 'Date' column
provisional_death["Date"] = provisional_death["Date"].apply(parse_date)

In [76]:
provisional_death

,State,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State Name,Predicted Value,Date
0,AK,2015,April,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",0.0,100,0.000000,Alaska,0.0,2015-04-01
1,AK,2015,April,12 month-ending,Heroin (T40.1),0.0,100,0.000000,Alaska,0.0,2015-04-01
2,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),0.0,100,0.000000,Alaska,0.0,2015-04-01
3,AK,2015,April,12 month-ending,Number of Drug Overdose Deaths,126.0,100,0.000000,Alaska,126.0,2015-04-01
4,AK,2015,April,12 month-ending,Cocaine (T40.5),0.0,100,0.000000,Alaska,0.0,2015-04-01
...,...,...,...,...,...,...,...,...,...,...,...
65158,YC,2023,September,12 month-ending,Percent with drugs specified,99.0,100,0.297994,New York City,0.0,2023-09-01
65159,YC,2023,September,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",2584.0,100,0.297994,New York City,2678.0,2023-09-01
65160,YC,2023,September,12 month-ending,Cocaine (T40.5),1670.0,100,0.297994,New York City,1728.0,2023-09-01
65161,YC,2023,September,12 month-ending,Number of Deaths,56377.0,100,0.297994,New York City,0.0,2023-09-01
65162,YC,2023,September,12 month-ending,Psychostimulants with abuse potential (T43.6),252.0,100,0.297994,New York City,262.0,2023-09-01

In [55]:
provisional_death.dtypes

State                                    object
Year                                     object
Month                                    object
Period                                   object
Indicator                                object
Data Value                              float64
Percent Complete                         object
Percent Pending Investigation           float64
State Name                               object
Predicted Value                         float64
Date                             datetime64[ns]
dtype: object

In [56]:
provisional_death['Date'] = provisional_death['Date'].astype('int64').astype('int32')

#provisional_death['Date'] = pd.to_datetime(provisional_death['Date']).astype(int.64)

In [57]:
provisional_death.dtypes

State                             object
Year                              object
Month                             object
Period                            object
Indicator                         object
Data Value                       float64
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                  float64
Date                               int32
dtype: object

In [58]:
provisional_death.dtypes

State                             object
Year                              object
Month                             object
Period                            object
Indicator                         object
Data Value                       float64
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                  float64
Date                               int32
dtype: object

In [59]:
provisional_death

,State,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State Name,Predicted Value,Date
0,AK,2015,April,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",0.0,100,0.000000,Alaska,0.0,1506934784
1,AK,2015,April,12 month-ending,Heroin (T40.1),0.0,100,0.000000,Alaska,0.0,1506934784
2,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),0.0,100,0.000000,Alaska,0.0,1506934784
3,AK,2015,April,12 month-ending,Number of Drug Overdose Deaths,126.0,100,0.000000,Alaska,126.0,1506934784
4,AK,2015,April,12 month-ending,Cocaine (T40.5),0.0,100,0.000000,Alaska,0.0,1506934784
...,...,...,...,...,...,...,...,...,...,...,...
65158,YC,2023,September,12 month-ending,Percent with drugs specified,99.0,100,0.297994,New York City,0.0,-1044447232
65159,YC,2023,September,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",2584.0,100,0.297994,New York City,2678.0,-1044447232
65160,YC,2023,September,12 month-ending,Cocaine (T40.5),1670.0,100,0.297994,New York City,1728.0,-1044447232
65161,YC,2023,September,12 month-ending,Number of Deaths,56377.0,100,0.297994,New York City,0.0,-1044447232
65162,YC,2023,September,12 month-ending,Psychostimulants with abuse potential (T43.6),252.0,100,0.297994,New York City,262.0,-1044447232

In [60]:
provisional_death.dtypes

State                             object
Year                              object
Month                             object
Period                            object
Indicator                         object
Data Value                       float64
Percent Complete                  object
Percent Pending Investigation    float64
State Name                        object
Predicted Value                  float64
Date                               int32
dtype: object

In [61]:
provisional_death.head()

,State,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State Name,Predicted Value,Date
0,AK,2015,April,12 month-ending,"Synthetic opioids, excl. methadone (T40.4)",0.0,100,0.0,Alaska,0.0,1506934784
1,AK,2015,April,12 month-ending,Heroin (T40.1),0.0,100,0.0,Alaska,0.0,1506934784
2,AK,2015,April,12 month-ending,Natural & semi-synthetic opioids (T40.2),0.0,100,0.0,Alaska,0.0,1506934784
3,AK,2015,April,12 month-ending,Number of Drug Overdose Deaths,126.0,100,0.0,Alaska,126.0,1506934784
4,AK,2015,April,12 month-ending,Cocaine (T40.5),0.0,100,0.0,Alaska,0.0,1506934784

In [71]:
#nationwide tab in case 
  # nation_tab=st.tabs(['Nationwide'])
analyze_tab,nation_tab = st.tabs(['Details','Nationwide'])
#ading death for data value 
death=provisional_death['Data Value']
#filter: 
provisional_death_filter=provisional_death[provisional_death['Data Value']==death]
#TRIAL FOR LINE CHART FOR THE NATION US 
#with nation_tab:

In [75]:
######TRIAL FOR NATIONWIDE #######TRIAL FOR LINE CHART FOR THE NATION US  ITWORKS!!! DONT DELETE!!!!!!!!#########################
#AVG DEATH OVER TIME !!!!!!!!
#adding death for data value 

death=provisional_death['Data Value']
year=provisional_death['Year']
predicted=provisional_death['Predicted Value']
# Filter data
filtered_data = provisional_death.copy()  # Make a copy of the original DataFrame
filtered_data = filtered_data[filtered_data['Data Value'] == death]
predicted_data = provisional_death.groupby('Year')['Predicted Value'].mean().reset_index()



# Prepare the data for predicted values
predicted_data = provisional_death.groupby('Year')['Predicted Value'].mean().reset_index()
chart_data = filtered_data.groupby('Year')['Data Value'].mean().reset_index()

# Plotting with Altair ITS WORKING 
chart = alt.Chart(chart_data).mark_line(color="blue").encode(
    x=alt.X("Year", axis=alt.Axis(format="")),
    y=alt.Y("Data Value", scale=alt.Scale(zero=False), title="Average Death - 12 month period")
)

# Display the chart
st.altair_chart(chart)

TypeError: datetime64 type does not support sum operations